n1 = float(input('Digite a nota 1: '))
n2 = float(input('Digite a nota 2: '))
n3 = float(input('Digite a nota 3: '))
n4 = float(input('Digite a nota 4: '))
print(f'A média entre as notas é de {(n1+n2+n3+n4)/2:.2f}')
